

name: Build and deploy a container to an Azure Web App


on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository 
        uses: actions/checkout@v4
      - name: Docker Build
        uses: actions/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
           username: ${{secrets.DOCKER_USERNAME}}
           password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build & Push
        uses: docker/build-push-action@v6.15.0
        with:
           context: .
           tag: ${{secrets.DOCKER_USERNAME}}/webapp:latest
           push: true
           

          
    

      
