# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kishor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f6b3952c121340c5b8164801b403e85b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a3f9e100a3f643c0975d93a6598d0f05 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6b3952c121340c5b8164801b403e85b }}/webapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kishor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a7084451e5bd4efca41e9e8e2ed1cc3d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f6b3952c121340c5b8164801b403e85b }}/webapp:${{ github.sha }}'